/* @flow */
export default [
  {id: 1, name: 'Apple', price: 5, prefectures: 'Aomori'},
  {id: 2, name: 'Orange', price: 8, prefectures: 'Ehime'},
  {id: 3, name: 'peach', price: 10, prefectures: 'Okayama'},
  {id: 4, name: 'Strawberry', price: 7, prefectures: 'Mie'},
  {id: 5, name: 'Banana', price: 1, prefectures: 'Chiba'},
  {id: 6, name: 'Grape', price: 40, prefectures: 'Tochigi'},
  {id: 7, name: 'Blue Apple', price: 10, prefectures: 'Aomori'},
  {id: 8, name: 'Blue Apple', price: 10, prefectures: 'Iwate'},
  {id: 9, name: 'Apple（Red Dream）', price: 99, prefectures: 'Iwate'},
  {id: 10, name: 'Apple（Pearl）', price: 1000, prefectures: 'Akita'},
  {id: 11, name: 'Apple1', price: 5, prefectures: 'Aomori'},
  {id: 12, name: 'Orange1', price: 8, prefectures: 'Ehime'},
  {id: 13, name: 'peach1', price: 10, prefectures: 'Okayama'},
  {id: 14, name: 'Strawberry1', price: 7, prefectures: 'Mie'},
  {id: 15, name: 'Banana1', price: 1, prefectures: 'Chiba'},
  {id: 16, name: 'Grape1', price: 40, prefectures: 'Tochigi'},
  {id: 17, name: 'Blue 森Apple1', price: 10, prefectures: 'Aomori'},
  {id: 18, name: 'Blue Apple1', price: 10, prefectures: 'Iwate'},
  {id: 19, name: 'Apple（Red Dream）1', price: 99, prefectures: 'Iwate'},
  {id: 20, name: 'Apple（Pearl）1', price: 99, prefectures: 'Akita'},
  {id: 21, name: 'Apple2', price: 5, prefectures: 'Aomori'},
  {id: 22, name: 'Orange2', price: 8, prefectures: 'Ehime'},
  {id: 23, name: 'peach2', price: 10, prefectures: 'Okayama'},
  {id: 24, name: 'Strawberry2', price: 7, prefectures: 'Mie'},
  {id: 25, name: 'Banana2', price: 1, prefectures: 'Chiba'},
  {id: 26, name: 'Grape2', price: 40, prefectures: 'Tochigi'},
  {id: 27, name: 'Blue 森Apple2', price: 10, prefectures: 'Aomori'},
  {id: 28, name: 'Blue Apple2', price: 10, prefectures: 'Iwate'},
  {id: 29, name: 'Apple（Red Dream）2', price: 99, prefectures: 'Iwate'},
  {id: 30, name: 'Apple（Pearl）2', price: 99, prefectures: 'Akita'},
];
